name: pysatgeo
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - gdal
  - rasterio
  - rioxarray
  - geopandas
  - shapely
  - xarray
  - pyarrow
  - scikit-learn
  - matplotlib
  - mapclassify
  - scipy
  - pandas
  - numpy
  - pytest
  - pip:
      - -r requirements_dev.txt
